### PR TITLE
fix: resolve the issue of unable to delete pictures.

### LINKED ISSUE #7: 无法移除已添加的图片
### Halo 版本
2.4.1 

### 插件版本
1.0.0

### 问题描述
在编辑器添加图片之后，点击删除按钮无效。

/kind bug
/assign

### PR DESCRIPTION
**Pull request by LIlGG**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

修复移除已添加图片时，由于变量名错误导致图片无法移除的问题。

#### Which issue(s) this PR fixes:

Fixes #7 

#### Special notes for your reviewer:

测试方式：

1. 安装可测试插件 [plugin-moments-1.0.0-SNAPSHOT.jar.zip](https://github.com/halo-sigs/plugin-moments/files/11147044/plugin-moments-1.0.0-SNAPSHOT.jar.zip)
2. 前往瞬间页面添加图片
3. 点击删除按钮，查看是否能够正常移除已添加图片

#### Does this PR introduce a user-facing change?

```release-note
修复无法移除已添加图片的问题。
```

### CODE REVIEW

**Review by ruibaby — APPROVED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
@LIlGG 有冲突需要解决。

```
src/main/resources/console/main.js

```

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
